language: python
dist: xenial
sudo: true

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VETUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run flake8
  - pipenv run pytest --cov=pro

after_success:
  - pipenv run codecov
