# Generated by Django 3.2 on 2021-04-29 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 29, 21, 0, 21, 279660, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
